atualização install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -179,6 +179,18 @@ systembeepoff() {
     rmmod pcspkr
     echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf ;}
 
+deploydotfiles() {
+    installpkg "stow"
+
+    putgitrepo "$dotfilesrepo" "/home/$name/.dotfiles" "$repobranch"
+    putgitrepo "$scriptsrepo" "/home/$name/.scripts" "$repobranch"
+
+    stow -vSt /home/$name/.local/bin /home/$name/.scripts/*
+    export PATH=/home/$name/.local/bin:$PATH
+
+    destow -s /home/$name/.dotfiles -t /home/$name
+}
+
 finalize(){ \
     printf "Preparing welcome message...\n"
     printf "\nAll done!\n"
@@ -233,7 +245,8 @@ sed -i "s/^#ParallelDownloads = 8$/ParallelDownloads = 5/;s/^#Color$/Color/" /et
 # Use all cores for compilation.
 sed -i "s/-j2/-j$(nproc)/;s/^#MAKEFLAGS/MAKEFLAGS/" /etc/makepkg.conf
 
-manualinstall yay-bin || error "Failed to install AUR helper."
+installpkg "yay"
+# manualinstall yay-bin || error "Failed to install AUR helper."
 
 # The command that does all the installing. Reads the progs.csv file and
 # installs each needed program the way required. Be sure to run this only after
@@ -245,26 +258,15 @@ printf "\nLARBS Installation\n"
 printf "\nFinally, installing \`libxft-bgra\` to enable color emoji in suckless software without crashes.\n"
 yes | sudo -u "$name" $aurhelper -S libxft-bgra-git >/dev/null 2>&1
 
-# Install the dotfiles in the user's home directory
-installpkg "stow"
-
-mkdir /home/$name/.dotfiles
-mkdir /home/$name/.shellscripts
-mkdir /home/$name/.local/bin
-
-putgitrepo "$dotfilesrepo" "/home/$name/.dotfiles" "$repobranch"
-putgitrepo "$scriptsrepo" "/home/$name/.scripts" "$repobranch"
-
-# TODO: (de)stow dotfiles
-
-# Create default urls file if none exists.
-
 # Most important command! Get rid of the beep!
 systembeepoff
 
 # Make zsh the default shell for the user.
 chsh -s /bin/zsh "$name" >/dev/null 2>&1
 sudo -u "$name" mkdir -p "/home/$name/.cache/zsh/"
+
+# Install the dotfiles in the user's home directory
+deploydotfiles
 
 # dbus UUID must be generated for Artix runit.
 dbus-uuidgen > /var/lib/dbus/machine-id
@@ -286,4 +288,4 @@ newperms "%wheel ALL=(ALL) ALL #LARBS
 
 # Last message! Install complete!
 finalize
-c
+
